---
dist: xenial
os: ["linux"]
language: python
python:
  - 3.7
git:
  submodules: true
cache: pip

install:
  - python -m pip install coveralls
  - python -m pip install -r requirements.txt
  - python -m pip install -r requirements-test.txt

script:
  - make _test
  - coveralls
