---
name: lint-python
"on":
  pull_request: {}
  push: { branches: [master] }

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements
        # NOTE: container lacks OS dist for testresources/launchpadlib
        run: |
          pip install testresources==2.0.1
          make _deps

      - name: Test
        run: make _test
