---
name: deploy-prod

"on":
  push:
    branches: [master]

concurrency: prod

jobs:
  deploy-prod:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clean
        run: make clean

      # TODO: database upgrades as part of this? Or app handles that?
      #  That means also backups and a retention policy
      - name: Install
        run: make install

      # NOTE: I added a /etc/sudoers rule, to avoid the password prompt
      # See: https://unix.stackexchange.com/a/606476/290740
      - name: Restart Service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl restart ntserv
