---
name: deploy-dev
"on":
  push: {}

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clean up & Init
        run: |
          rm -rf .venv
          make init
          make deps

      - name: Verify
        run: make lint test

      # TODO: database upgrades as part of this? Or app handles that?
      - name: Install & Restart Service
        run: |
          make install
          systemctl --user restart ntserv.service
