---
name: CI
"on":
  push: {}

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check environment
        run: |
          pwd
          uname -a
          echo $PATH
          ls -la
          ls -la /
          dpkg -l
          psql -l
          curl localhost:20000
