---
name: CI
"on":
  push: {}

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Verify
        run: make lint test

      # TODO: database upgrades as part of this? Or app handles that?
      - name: Install & Restart Service
        run: |
          make install
          systemctl --user restart ntserv.service
