---
name: test-win32

"on":
  push: {}

jobs:
  windows-latest:
    runs-on: windows-latest

    steps:
      - name: Configure Line Endings / git / LF
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3
        # NOTE: skip submodules, we don't use DB. See below NOTE.

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # NOTE: Skip Postgres setup for Windows, running w/o has value of its own
      - name: Install requirements
        run: make _deps

      - name: Run Tests
        run: make _test

      - name: Run linters
        run: make _lint
